# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blockchain?
email: tyler@pennantcreative.ca
description: > # this means to ignore newlines until "baseurl:"
  This site ismy attempt at explaining the concepts behind blockchain to those with little or no computer science background.
baseurl: /blockchain # the subpath of your site, e.g. /blog
url: "http://pennantcreative.github.io" # the base hostname & protocol for your site
twitter_username: pennantcreative
github_username:  pennantcreative

# Build settings
markdown: kramdown
